name: quran_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/surah/
    - assets/translation/ar/
    - assets/translation/en/
    - assets/translation/id/
    - assets/icon/

  fonts:
    - family: nam
      fonts:
        - asset: assets/fonts/surah_nam.ttf # خط أسماء السور والفهرس الجديد

    - family: bsm60
      fonts:
        - asset: assets/fonts/bsmla60.ttf # خط البسملة المطور (رقم 60)

    - family: nss
      fonts:
        - asset: assets/fonts/sura_nss.otf # 🛠️ تم تصحيح الاسم والامتداد هنا

    - family: quran_num
      fonts:
        - asset: assets/fonts/123456.ttf # خط الترقيم الدائري الذكي للآيات

    - family: jzu12
      fonts:
        - asset: assets/fonts/jzu12.ttf # خط الأجزاء العثماني الجديد

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
