name: quran_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  just_audio: ^0.9.43
  path_provider: ^2.1.3
  dio: ^5.5.0
  archive: ^3.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/surah/
    - assets/translation/ar/
    - assets/translation/en/
    - assets/translation/id/
    - assets/icon/
    - assets/audiourls/
    - assets/data/readers.json

  fonts:
    - family: nam
      fonts:
        - asset: assets/fonts/surah_nam.ttf 

    - family: bsm60
      fonts:
        - asset: assets/fonts/bsmla60.ttf 

    - family: nss
      fonts:
        - asset: assets/fonts/sura_nss.otf 

    - family: quran_num
      fonts:
        - asset: assets/fonts/123456.ttf 

    - family: jzu12
      fonts:
        - asset: assets/fonts/jzu12.ttf 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
