name: quran_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # المكتبة اللازمة لحفظ الإعدادات (الوضع الليلي والخط)
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
  
  # تحديد المسارات التي تحتوي على ملفاتك لضمان قراءتها
  assets:
    - assets/data/
    - assets/surah/
    - assets/icon/

  # تعريف الخط المخصص
  fonts:
    - family: ahmed
      fonts:
        - asset: assets/fonts/ahmed.ttf

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

# إعدادات أيقونة التطبيق
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png" 
  min_sdk_android: 21
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0 # أو أي إصدار حديث متوافق
